### ISSUE TITLE
Machine agent install seems to look for db-agent path

### ISSUE THREAD

**Issue by pk-z1** [Appdynamics/appdynamics-ansible#71]
Hello - I'm trying to install the machine agent on linux, but it appears to look for the db-agent path.  Am I missing something here?

#ansible-playbook -i hosts-linux machine.yaml 

.
.
.

TASK [appdynamics.agents.logger : Copy the log4j file down to update it localy] *************************************************************************
fatal: [10.0.110.37]: FAILED! => {"changed": false, "msg": "file not found: /opt/appdynamics/db-agent/conf/logging/log4j.xml"}

**Comment by jpadmin** [comment]
You won't face that issue if you try to run the automation using latest version ansible

**Comment by iogbole** [comment]
FYI @v-zhuravlev

**Comment by v-zhuravlev** [comment]
hi @pk-z1 , thanks for reporting. It Would be great if you can provide more info in order to replicate this issue:
ansible version
appdynamics-ansible collection version
machine.yaml contents if it is custom playbook
any machine agent related variables you may set elsewhere( in inventory, vars file etc)

@jpadmin , do you mean ansible version or collection version?

**Comment by v-zhuravlev** [comment]
Can confirm this error for ansible 2.9

**Comment by v-zhuravlev** [comment]
as a workaround, please upgrade to 2.10 + or remove `agent_log_level: debug` from vars or change to `info`

**Comment by pk-z1** [comment]
Thanks @v-zhuravlev - I also validated that `agent_log_level: "info"` works as well.

**Comment by jpadmin** [comment]
@v-zhuravlev , I can confirm that the automation works perfectly using latest ansible software with python3 as the interpreter

**Comment by v-zhuravlev** [comment]
Found what was the issue in 2.9. Fixed in #72 . Will be available in the next release.

**Comment by v-zhuravlev** [comment]
available in 21.6.0
